name: flutter_plugin_record_329_example
description: "The flutter voice recording plug-in,provides the recording animation and the recording successfully returns to the recording file path"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flustars: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_plugin_record_329:
    path: ../
flutter:
  uses-material-design: true
