name: flutter_plugin_record_329
description: "使用Flutter实现 仿微信录音的插件 支持 Flutter 3.29"
version: 1.0.2
homepage: https://github.com/yxwandroid/flutter_plugin_record_329
#publish_to: none

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: record.wilson.flutter.com.flutter_plugin_record_329
        pluginClass: FlutterPluginRecord329Plugin
      ios:
        pluginClass: FlutterPluginRecord329Plugin

  uses-material-design: true
  assets:
    - images/voice_volume_1.png
    - images/voice_volume_2.png
    - images/voice_volume_3.png
    - images/voice_volume_4.png
    - images/voice_volume_5.png
    - images/voice_volume_6.png
    - images/voice_volume_7.png

